server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:maglev.proxy.rlwy.net}:${PGPORT:11817}/${PGDATABASE:railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:kwrUtMDTTiJouUinEzojFPUafziUZAnX}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
