server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:shuttle.proxy.rlwy.net}:${PGPORT:36506}/${PGDATABASE:railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:HNQjlgpTsNTeFeCySxBMCdbXyCaJpYEG}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
