server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:trolley.proxy.rlwy.net}:${PGPORT:37324}/${PGDATABASE:railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:enCgwjEOfvppzwyEXltXtHkdWobQvUNd}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
