server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:postgres-djif.railway.internal}:${PGPORT:5432}/${PGDATABASE:railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:ZijwfXdvQpTwYhWoWkTgwrmcqEapqVGY}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
